### ISSUE TITLE
Hello, my dear sir, there are serval issues.

### ISSUE THREAD

**Issue by SwordHolderSH** [suraj-maniyar/Deep-Visual-Attention-Prediction#1]
Dear author
I'm working on this area recently. I have cloned this project and configured the environment, but it found that some files and folders are not in the right place, and the system prompts: "No such file or directory: 'data/train/images/salMap_00000.jpg' ".
I would like to ask you, dear sir, can this open source project be used normally? If can, which folder should the training-set or test-set, and where the folder should be placed in? 
Please leave me some help, my dear author~

**Comment by hardi-desai** [comment]
Please confirm whether you are trying to run it using google collab or locally on your PC. Also, as mentioned in the report, we have used the SALICON API for generating the training and testing images.
