### ISSUE TITLE
train_data 

### ISSUE THREAD

**Issue by hello-bin** [suraj-maniyar/Deep-Visual-Attention-Prediction#2]
Hello,Can you share a link to download the train data and label. I have download the SALICON data. But I do not know where I  can find the groundtruth. Wait for your reply.

**Comment by suraj-maniyar** [comment]
The download link has been provided in the first line of the IPython Notebook in the src folder.
( https://www.dropbox.com/s/ttc9hmcca04lc02/sal_data.zip?dl=0 )

**Comment by hello-bin** [comment]
In fact I have tried  the link to download. But The Browser tell me cannot connect to Servers. Maybe it due to Great Firewall of China？
